"""ideaGen URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from ideas.views import *
from ideasGen import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('loading/', loading_page, name='loading'),
    path('generated/', generated, name='generated'),
    path('autogenerated/', autogenerated, name='autogenerated'),
    path('ownidea/', OwnIdea.as_view(), name='ownidea'),
    path('', IdeasHome.as_view(), name='home'),
    path('contgener/', contgener, name='contgener')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
